from __future__ import annotations

from datetime import UTC, datetime
from html import escape
from ipaddress import ip_address
import json
from pathlib import Path
from urllib.parse import urlparse

from testpilot.contracts.runner import ContractError, RunManifest, RunResult
from testpilot.storage.database import Database


REQUIRED_LOCAL_ARTIFACTS = {
    "junit": "junit.xml",
    "html": "report.html",
    "log": "runner.log",
}


def is_loopback_base_url(value: object) -> bool:
    """Return whether an environment URL is explicitly bound to this host."""
    try:
        parsed = urlparse(str(value or "").strip())
        host = (parsed.hostname or "").strip().lower()
        if parsed.scheme not in {"http", "https"} or not host:
            return False
        return host == "localhost" or ip_address(host).is_loopback
    except ValueError:
        return False


def write_runner_error_evidence(artifacts_root: Path, run_id: str, message: str) -> dict:
    """Persist the minimum evidence set when a Runner cannot create its own result."""
    root = artifacts_root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(UTC).isoformat(timespec="seconds")
    safe_message = escape(message)
    artifacts = {
        "root": str(root), "junit": "junit.xml", "html": "report.html",
        "log": "runner.log", "runner_log": "runner.log",
    }
    result = {
        "schema_version": "1.0", "run_id": run_id, "status": "error",
        "started_at": timestamp, "finished_at": timestamp,
        "summary": {"total": 0, "passed": 0, "failed": 0, "error": 1, "skipped": 0},
        "cases": [], "artifacts": artifacts, "error": message,
        "metadata": {"failure_phase": "initialization"},
    }
    (root / "runner.log").write_text(f"[{timestamp}] {message}\n", encoding="utf-8")
    (root / "junit.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<testsuite name="external-runner" tests="1" errors="1" time="0">'
        f'<testcase classname="runner" name="initialization"><error message="{safe_message}" />'
        '</testcase></testsuite>\n', encoding="utf-8"
    )
    (root / "report.html").write_text(
        '<!doctype html><meta charset="utf-8"><title>Runner 初始化失败</title>'
        f'<h1>Runner 初始化失败</h1><pre>{safe_message}</pre>', encoding="utf-8"
    )
    (root / "result.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return result


def validate_local_runner_artifacts(artifacts_root: Path, result_payload: dict) -> None:
    """Validate a local Runner's evidence without trusting reported paths.

    A locally started Runner receives an artifacts directory generated by the
    platform.  Its result must point back into that exact directory and expose
    the minimum Phase 1 evidence set.  Docker/CI imports intentionally do not
    use this helper because their mounted paths need not match the desktop path.
    """
    root = artifacts_root.resolve()
    artifacts = result_payload.get("artifacts") or {}
    reported_root = str(artifacts.get("root") or "").strip()
    if not reported_root:
        raise ContractError("本地 Runner 的 result.json 缺少 artifacts.root")
    try:
        if Path(reported_root).resolve() != root:
            raise ContractError("本地 Runner 的 artifacts.root 必须等于平台生成的产物目录")
    except OSError as exc:
        raise ContractError(f"无法校验本地 Runner 产物目录：{exc}") from exc

    for key, default_name in REQUIRED_LOCAL_ARTIFACTS.items():
        declared = str(artifacts.get(key) or default_name).strip()
        candidate = Path(declared)
        candidate = candidate if candidate.is_absolute() else root / candidate
        try:
            candidate = candidate.resolve()
            candidate.relative_to(root)
        except (OSError, ValueError) as exc:
            raise ContractError(f"本地 Runner 产物 {key} 不在受控目录内") from exc
        if not candidate.is_file():
            raise ContractError(f"本地 Runner 缺少必需产物：{key}（{default_name}）")


def queue_external_run(db: Database, manifest_payload: dict) -> int:
    """Validate a platform manifest and persist a runner task without executing it.

    Execution remains a later concern: the platform may hand this task to a
    local process, Docker, or CI worker.  Persisting the immutable manifest
    first gives every execution path the same audit boundary.
    """
    manifest = RunManifest.from_dict(manifest_payload)
    adapter = db.get_project_adapter_by_key(manifest.project_id)
    if adapter is None:
        raise ContractError(f"未注册项目 Adapter：{manifest.project_id}")
    runner = db.get_runner_by_name(int(adapter["project_id"]), manifest.runner_name)
    if runner is None:
        raise ContractError(f"项目 {manifest.project_id} 未注册 Runner：{manifest.runner_name}")
    if not runner["enabled"]:
        raise ContractError(f"Runner 已禁用：{manifest.runner_name}")
    if runner["version"] != manifest.runner_version:
        raise ContractError(
            f"Runner 版本不匹配：已注册 {runner['version']}，Manifest 为 {manifest.runner_version}"
        )
    if runner["manifest_schema_version"] != manifest.schema_version:
        raise ContractError(
            f"Runner Manifest 协议不匹配：已注册 {runner['manifest_schema_version']}，"
            f"Manifest 为 {manifest.schema_version}"
        )
    environment = db.get_environment(int(adapter["project_id"]), manifest.environment_id)
    if environment is None:
        raise ContractError(f"项目 {manifest.project_id} 未配置环境：{manifest.environment_id}")
    selected_markers = {marker.lower() for marker in manifest.selection.markers}
    if "mutation" in selected_markers and not manifest.policy.allow_mutation:
        raise ContractError("选中了 mutation 套件，但 Manifest 未显式允许 mutation")
    if manifest.policy.allow_mutation and not environment["capabilities"].get("allow_mutation", False):
        raise ContractError(f"环境 {manifest.environment_id} 不允许 mutation 执行")
    if manifest.policy.allow_mutation and not is_loopback_base_url(environment.get("base_url")):
        raise ContractError("mutation 套件只能在 localhost 或 127.0.0.0/8 环回测试环境执行")
    return db.create_runner_run(int(runner["project_id"]), int(runner["id"]), manifest.to_dict())


def complete_external_run(db: Database, run_id: int, result_payload: dict) -> None:
    """Validate and attach a runner result to an already queued platform task."""
    result = RunResult.from_dict(result_payload)
    queued_run = db.get_runner_run(run_id)
    if queued_run is None:
        raise ContractError(f"外部 Runner 运行记录不存在：{run_id}")
    if queued_run["status"] not in {"queued", "running"}:
        raise ContractError(f"外部 Runner 运行已结束，不能重复归档：{run_id}")
    expected_run_id = str(queued_run["manifest"].get("run_id") or "")
    if result.run_id != expected_run_id:
        raise ContractError(f"Result run_id 与入队 Manifest 不一致：{result.run_id} != {expected_run_id}")
    db.finish_runner_run(run_id, result.to_dict())
